### ISSUE TITLE
Update README with code examples

### ISSUE THREAD

**Issue by yakovmanshin** [yakovmanshin/YMKit#12]

**Comment by Seniru** [comment]
Couldn't this be done with an automated documentation tool? So it will reduce the time wiring documentation again. And my idea is to move the documentation to a separate file instead of the README

**Comment by yakovmanshin** [comment]
@Seniru I think you’re right. A separate file (or a set of files) is a better place for the comprehensive documentation.

In README, I just want to give a taste of what kind of tasks this framework can help with.

Thanks for your suggestion!
